### ISSUE TITLE
Afficher l'état des services du projet

### ISSUE THREAD

**Issue by clairenollet** [dnum-mi/dso-console#120]
## US

ETU je veux visualiser le statut des services associés à mon projet.

## TODO 

- à redéfinir : obtenir l'état des services via playbooks ?
- fetch sur url du service ? get `healthz` de chaque outil => edit : en fait non parce qu'on veut bien savoir si on tombe sur une 404 pour le projet demandé et pas juste l'état de santé de tout le gitlab de la forge par ex.

**Comment by ArnaudTa** [comment]
Le dashboard n'a pas encore de fonction bien défini, mais est-ce que cela vaut le coup d'afficher les `created` ? tout afficher serait un doublon de la page "Mes projets"
