### ISSUE TITLE
BUG : username du robot lors de la création d'un projet depuis la console

### ISSUE THREAD

**Issue by plec** [dnum-mi/dso-console#149]
Lors de la création d'un projet depuis la console DSO, le nom du robot QUAY présent dans les secrets n'est pas correcte, il manque la partie organisation dans son nom de la forme : nom_organisation+nom_projet

**Comment by ArnaudTa** [comment]
mauvais repo, tu peux refaire le ticket sur [dso-playbooks](https://github.com/dnum-mi/dso-playbooks)
