### ISSUE TITLE
Generation d'un fichier gitlab-ci-dso.yml

### ISSUE THREAD

**Issue by plec** [dnum-mi/dso-console#152]
### US
ETQ Owner de repo, je souhaite que la console DSO crée un fichier gitlab-ci dédié à DSO (.gitlab-ci-dso.yml) afin que celui-ci n'entre pas en conflit avec un fichier gitlab-ci déjà existant sur mon projet et utilisé pour une CI autre que DSO. Il faut modifier la création du projet dans gitlab afin d'indiquer le nom du fichier gitlab-ci-dso dans la configuration CI/CD du projet.

**Comment by clairenollet** [comment]
cf #67
