### ISSUE TITLE
[Contrôle de longueur] la longueur du namespace ne doit pas dépasser 63 caractères  

### ISSUE THREAD

**Issue by plec** [dnum-mi/dso-console#192]
La longueur du namespace dans openshift doit faire moins de 63 caractères or il est construit avec : 
nom de l'orga + '-' + nom projet + '-' + nom env (dev/prod/pprod)

Ce nom ne doit pas faire plus de 63 caractères, il faut ajouter une contrainte sur la longueur du nom proj et nom repo pour que la concaténation soit <= à 63 caractères.

**Comment by clairenollet** [comment]
`remainingCharacters = 61` (63 moins 2 tirets)
- `remainingCharacters = remainingCharacters - longestEnvironmentName.length`
- choix de l'orga => `remainingCharacters = remainingCharacters - organizationName.length`
- choix du nom du projet => `project.length <= remainingCharacters`
