### ISSUE TITLE
[admin] vue utilisateurs

### ISSUE THREAD

**Issue by LouisGongora** [dnum-mi/dso-console#268]
# US

ETadmin je souhaite pouvoir consulter la liste des utilisateurs

### Server
- [x] `isAdmin` clé à supprimer
- [x] créer un dossier `controllers/admin`
- [x] dedans créer un `user.js`
- [x] y mettre le `getAllUsers` (actuellement dans le `controllers/user.js`) 
- [x] contrôle d'accès : se baser sur le `req.session.user.group` : tableau qui doit contenir `'admin'`
ex `const isAdmin = req.session.user.group.includes('admin')`
- [x] sous-dossier `routes/admin` : `user.js`, préfix `/admin` 

### Client
- [x] appels api : `stores/admin` et fichier `user.js` pour les appels api
- [x] créer dossier `src/views/admin` et vue `ListUser.vue`
- [x] router : bloquer accès aux vue `admin` selon `isAdmin` dans un `beforeEnter`
- [x] Keycloak group admin

### Tests
- [x] TU côté server
- [x] test e2e, scénarios : je suis pas admin, j'essaie d'aller sur la page admin => je suis recalé / je suis admin, je vois les utilisateurs

**Comment by hanaura26** [comment]
- Projet et utilisateurs devraient être fini début de semaine prochaine
