### ISSUE TITLE
Installer CCAF via argoCD sur Coud PI Native (Aurahan)

### ISSUE THREAD

**Issue by hanaura26** [dnum-mi/dso-console#274]

**Comment by hanaura26** [comment]
- Premier déploiement effectué sur le cluster Openshift de pi gen 2 
- Seulement la partie mas-administration, pour commencer. Cet après midi j'enchaine avec le reste des composants de CCAF
- Peering avec Hugo Fontaine de Sopra Steria
- Redéploiement sur la zone s2, DR

**Comment by zkarahacane** [comment]
Relancer @titigmr pour kubeconfig

**Comment by zkarahacane** [comment]
kubeconfig ok
