### ISSUE TITLE
Gestion token avec keycloak

### ISSUE THREAD

**Issue by clairenollet** [dnum-mi/dso-console#32]
## TODO

- [ ] ~~stocker le token dans le `localStorage` : `window.localStorage.setItem('token', keycloak.token)`~~ ?
- [ ] ~~exiger un `token` et / ou `isTokenValid` au `beforeEach` des routes~~ token requis pour faire appel au server
- [x] Logout

## Commit
- https://github.com/dnum-mi/dso-console/pull/31/commits/592c025b75497a6595612542f9aa7e981b839903
- https://github.com/dnum-mi/dso-console/pull/31/commits/5aa50fb582c55e97179e2f0a5ff62fe464eb287b

https://www.keycloak.org/securing-apps/vue

**Comment by this-is-tobi** [comment]
Fixed
