### ISSUE TITLE
Associer un projet à un compte keycloak

### ISSUE THREAD

**Issue by clairenollet** [dnum-mi/dso-console#40]
## TODO

Réfléchir à la façon d'associer un `project` avec un ou plusieurs comptes keycloak : 
- quelles données peut-on récupérer de keycloak ? Dont une donnée susceptible d'être unique et de ne jamais changer (type id) ?
- ajouter dans l'objet `project` un tableau d'`ids` keycloak ?
- conserver cet `id` dans le store à la connexion et l'ajouter dans toutes les requêtes api ?

### Document `project`

```json
{
  "id": "7GGaOU_vw5fb-OHXsDBt9",
  "repo": [],
  "email": "claire.nollet@yahoo.fr",
  "orgName": "ministere-interieur",
  "services": [
    "argocd",
    "gitlab",
    "nexus",
    "quay",
    "sonarqube",
    "vault"
  ],
  "projectName": "Recette3"
}
```

**Comment by this-is-tobi** [comment]
Fixed
